restore go-check

diff --git a/.github/workflows/go-check.yml b/.github/workflows/go-check.yml
--- a/.github/workflows/go-check.yml
+++ b/.github/workflows/go-check.yml
@@ -1,50 +1,50 @@
-#name: Go Checks
-#
-#on:
-#  push:
-#    branches: [ master ]
-#  pull_request:
-#
-#jobs:
-#  go_checks:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#        with:
-#          submodules: recursive
-#      - uses: actions/setup-go@v2
-#        with:
-#          go-version: "1.18.x"
-#      - name: Install staticcheck
-#        run: go install honnef.co/go/tools/cmd/staticcheck@2022.1
-#      - name: Check that go.mod is tidy
-#        uses: protocol/multiple-go-modules@v1.0
-#        with:
-#          run: |
-#            go mod tidy
-#            if [[ -n $(git ls-files --other --exclude-standard --directory -- go.sum) ]]; then
-#              echo "go.sum was added by go mod tidy"
-#              exit 1
-#            fi
-#            git diff --exit-code -- go.sum go.mod
-#      - name: gofmt
-#        if: ${{ success() || failure() }} # run this step even if the previous one failed
-#        run: |
-#          out=$(gofmt -s -l .)
-#          if [[ -n "$out" ]]; then
-#            echo $out | awk '{print "::error file=" $0 ",line=0,col=0::File is not gofmt-ed."}'
-#            exit 1
-#          fi
-#      - name: go vet
-#        if: ${{ success() || failure() }} # run this step even if the previous one failed
-#        uses: protocol/multiple-go-modules@v1.0
-#        with:
-#          run: go vet ./...
-#      - name: staticcheck
-#        if: ${{ success() || failure() }} # run this step even if the previous one failed
-#        uses: protocol/multiple-go-modules@v1.0
-#        with:
-#          run: |
-#            set -o pipefail
-#            staticcheck ./... | sed -e 's@\(.*\)\.go@./\1.go@g'
-#
+name: Go Checks
+
+on:
+  push:
+    branches: [ master ]
+  pull_request:
+
+jobs:
+  go_checks:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: recursive
+      - uses: actions/setup-go@v2
+        with:
+          go-version: "1.18.x"
+      - name: Install staticcheck
+        run: go install honnef.co/go/tools/cmd/staticcheck@2022.1
+      - name: Check that go.mod is tidy
+        uses: protocol/multiple-go-modules@v1.0
+        with:
+          run: |
+            go mod tidy
+            if [[ -n $(git ls-files --other --exclude-standard --directory -- go.sum) ]]; then
+              echo "go.sum was added by go mod tidy"
+              exit 1
+            fi
+            git diff --exit-code -- go.sum go.mod
+      - name: gofmt
+        if: ${{ success() || failure() }} # run this step even if the previous one failed
+        run: |
+          out=$(gofmt -s -l .)
+          if [[ -n "$out" ]]; then
+            echo $out | awk '{print "::error file=" $0 ",line=0,col=0::File is not gofmt-ed."}'
+            exit 1
+          fi
+      - name: go vet
+        if: ${{ success() || failure() }} # run this step even if the previous one failed
+        uses: protocol/multiple-go-modules@v1.0
+        with:
+          run: go vet ./...
+      - name: staticcheck
+        if: ${{ success() || failure() }} # run this step even if the previous one failed
+        uses: protocol/multiple-go-modules@v1.0
+        with:
+          run: |
+            set -o pipefail
+            staticcheck ./... | sed -e 's@\(.*\)\.go@./\1.go@g'
+
